### ISSUE TITLE
Render multiple sheets

### ISSUE THREAD

**Issue by danielmcintosh1** [zeehio/condformat#11]
Current render2excel function only accepts a parameter for `workbook name`. 

Can you add a parameter for `sheetname` as the current default of sheet1 is not accessible and therefore I am not able to loop through a series of tables that I need to export.

**Comment by zeehio** [comment]
I haven't done extensive testing, but feel free to try it:

    devtools::install_github("zeehio/condformat")

And then do something like:

    library(condformat)
    data(iris)
    x <- condformat(iris)
    condformat2excel(x, "an_excel_file", "sheet1")
    condformat2excel(x, "an_excel_file", "sheet2")

I don't have much time to work on this right now, I hope this is useful :+1:

**Comment by danielmcintosh1** [comment]
This worked on my dataset! Much appreciated!
