### ISSUE TITLE
For loop seems to break condformat...

### ISSUE THREAD

**Issue by chaitanya-m** [zeehio/condformat#22]
Hi,

condformat works as intended without a loop, but strangely enough breaks when wrapped in one (I'd like to use it for large tables). I've put together a minimal example at:

https://tex.stackexchange.com/questions/516747/for-loop-breaks-condformat

Cheers.

**Comment by zeehio** [comment]
Thanks for the github issue. The question is answered in the stackexchange post. Thanks to your question I found out some deprecation warnings from rlang, that I just fixed on the github code.

I'm closing this issue, but feel free to comment / reopen if anything else pops up, or if you have further questions.
