### ISSUE TITLE
condformat2excel error

### ISSUE THREAD

**Issue by leeleavitt** [zeehio/condformat#23]
When attempting to use this line of code,
`condformat::condformat2excel(cf, "hello.xlsx",,T)`

I get the following traceback.

`6: stop(gettextf("'%s' is not an exported object from 'namespace:%s'",
       name, getNamespaceName(ns)), call. = FALSE, domain = NA)`
`5: getExportedValue(pkg, name)`
`4: xlsx::CellBlock.default`
`3: condformat2excelsheet(x, sheet)`
`2: condformat::condformat2excel(cf, "hello.xlsx", , T) at transcriptome_pharmer.r#363`
`1: heatMapper(geneDF)`

**Comment by zeehio** [comment]
I would need a minimal reproducible example to understand better what is going on.

Could you create one (e.g. using the [`reprex` package](https://www.tidyverse.org/help/))?

**Comment by zeehio** [comment]
I think I fixed the issue at 33308700aa0507cfd9b07d8260a47f44b10c932b. Could you please verify with `remotes::install_github("zeehio/condformat")`?
