### ISSUE TITLE
Latest Update version 0.9.0

### ISSUE THREAD

**Issue by kp-source** [zeehio/condformat#24]
Hi, 

Just wanted to say thank you, have been using the condformat package a lot with much success! On the recent release of version 0.9.0 I am encountering the following error when overwriting an existing xlsx workbook. 

Warning: Error in openxlsx::saveWorkbook: File already exists!

Any help is much appreciated.

**Comment by zeehio** [comment]
Thanks for the bug report!

I was doing some final tests and I would have submitted the package to CRAN tomorrow with the bug you described. Fortunately you were able to find it and report it!

I fixed the error from my phone, I would appreciate if you can test it.

I introduced the error while switching from the xlsx package to openxlsx, to avoid the rJava dependency. I hope there are no further surprises.

The excel export is very limited now, it should be easy to add support for further condformat rules. If you would like to use them feel free to open an issue for each rule you want to have support (e.g. "support rule_text_bold in Excel format") and I'll do my best to find time to add it.

Thanks again!

**Comment by kp-source** [comment]
Hi Sir, 

I just tested and received the same error. I am wondering if changing to overwrite = True would work.

  openxlsx::addWorksheet(wb, sheetName = sheet_name)
  }
  condformat2excelsheet(x, wb, sheet_name)
  openxlsx::saveWorkbook(wb, file = filename)
  openxlsx::saveWorkbook(wb, file = filename, overwrite = overwrite_wb)
  return(invisible(x))
}

Cheers!

**Comment by zeehio** [comment]
If you see the help page for `?condformat2excel` you will see that if you want to overwrite the workbook you must use `condformat2excel(..., overwrite_wb = TRUE)`

Does that work for you? Otherwise I'll take a look tomorrow to this issue.

**Comment by kp-source** [comment]
That did work, but I have lost the ability to overwrite the different sheets within the same workbook. For example I used the following code

condformat2excel(., filename = "test.xlsx", sheet_name = "Tab1",
                         overwrite_wb = False, overwrite_sheet = TRUE)

condformat2excel(., filename = "test.xlsx", sheet_name = "Tab12",
                         overwrite_wb = False, overwrite_sheet = TRUE)

With the overwrite workbook as TRUE I only see tab two for example. Do you have a workaround for this scenario? 

Cheers!

**Comment by zeehio** [comment]
I think I fixed now. Tomorrow I will add unit tests so  this feature is tested and doesn't break in the future again.

**Comment by zeehio** [comment]
Unit tests added at 6beea9add0cb8da2e46a01c72b39b79dfed3a244. Closing

**Comment by kp-source** [comment]
I just tested and was able to add sheets to an existing workbook! I really appreciate the updates.
