### ISSUE TITLE
openxlsx preparation for the new cran release

### ISSUE THREAD

**Issue by ycphs** [zeehio/condformat#26]
Hi,

I am the author of the [openxlsx ](https://github.com/ycphs/openxlsx) package. With the new version some of the test in your package fail.

Could you please check the dependencies?

If you have questions please feel free to contact me.

**Comment by zeehio** [comment]
Both errors in my package tests seem to be related to an `"object 'wb' not found` error in your package.

Could you please check the issue ycphs/openxlsx#92?

**Comment by zeehio** [comment]
Fixed upstream at https://github.com/ycphs/openxlsx/commit/343b42e52a3f4e4c210c5dcf2a13764e1b29c270
