### ISSUE TITLE
condformat in shiny?

### ISSUE THREAD

**Issue by mexindian** [zeehio/condformat#3]
Hi, I was wondering whether you had thought about providing a function to allow this to be used in Shiny Apps. So we would need some kinda `renderCondformat` for the server.R and then a `condformatOutput` for the ui...

Have you thought about this?

**Comment by zeehio** [comment]
Hi,

Shiny support added in the last commit. To try it use:

    devtools::install_github("zeehio/condformat")

Note that as long as htmlTable does not support pagination, long tables will be very long.

See https://github.com/gforge/htmlTable/issues/20 in case you want to implement pagination. 
Unfortunately neither @gforge (htmlTable maintainer) nor me have the time to work on it.

Thanks for the suggestion, I hope this Christmas commit is useful to you :smile:

**Comment by mexindian** [comment]
Trying to test. But I hate you because you have all your packages nicely updated, which forces me to update all my packages, which of course causes the typical rJava problems which cost me hours. ITS ALL YOUR FAULT! :)

Will confirm functionality asap.

**Comment by zeehio** [comment]
The rJava dependency is a nuisance  related to exporting to excel. Sorry.

I have tried to make it optional but I have been unable to do so in a way that R CMD check does not complain. Patches are welcome.

**Comment by mexindian** [comment]
rJava is just a general tax on the R community. omeday it'll get fixed. Anyway, tried your code and it works! So thanks very much! 

BTW... are you Latino and if so, would you like to join an R community for latinoamerica?

**Comment by zeehio** [comment]
I was able to successfully remove rJava from the condformat dependencies (now it is only suggested).

I am from Barcelona, so I am a bit far from latinoamerica. But who knows... maybe I move to America in the future :+1:

**Comment by mexindian** [comment]
It seems the latest version of either shiny or one of their dependencies, or this package or one if it's dependencies has broken condformat in shiny. 
![image](https://cloud.githubusercontent.com/assets/8094091/24970305/ba33af9a-1fab-11e7-98db-8a4473b4f97b.png)

Try this example after installing latest version of shiny:

```
library(shiny)
library(condformat)

server <- function(input, output) {
  output$distPlot <- renderCondformat({
    condformat(iris)
  })
}

ui <- fluidPage(
  condformatOutput("distPlot")
)

shinyApp(ui = ui, server = server)
```

Do you know why?
