### ISSUE TITLE
Suppress immediate condformat2grob output

### ISSUE THREAD

**Issue by interzoneboy** [zeehio/condformat#30]
I note that when I call `condformat2grob` the plot is immediately generated and displayed, even if what I'm trying to do is to store the grob in a variable for layout with `ggarrange` or `grid.arrange`. In my case, where I have two conditionally formatted tables and one ggplot layed out with `ggarrange`, this causes knitr to output first the one table, then the second one, and then the composite figure (which itself is just fine).

I seem to have fixed this myself by altering the source code -- I commented out two function calls right at the end of the `condformat2grob` function:  `grid::grid.newpage()` and `grid::grid.draw(gridobj)`. The subsequent call (`invisible(gridobj)`) seems to return the grob properly, and my `ggarrange` layout works as it should.

Knocking out these two lines probably messed up something elsewhere (so not going to make a PR out of this), but for my purposes it works perfectly. Thanks for your work on this -- it's fantastic!

**Comment by zeehio** [comment]
Hi! Thanks for your feedback. It's nice to know the package has users!

I believe your solution is actually a very good approach.

If you want to create a pull request, I would review and merge one that:

- Adds a `draw=TRUE` argument to `condformat2grob()`.
- puts the `grid.newpage()` and `grid.draw()` calls within an `if (draw) {...}`
- Adds the corresponding documentation
- Adds a NEWS entry

Would you be up to do that?

**Comment by interzoneboy** [comment]
Yes indeed. Pull request submitted #31

**Comment by zeehio** [comment]
Merged and on its way to CRAN :+1:
