### ISSUE TITLE
Getting "## NULL" above table in knitr PDF output

### ISSUE THREAD

**Issue by JohnTarr** [zeehio/condformat#4]
This package is awesome, but I've noticed something that may be a bug.

When knitting to PDF, `## NULL` appears before the table output. Apparently, this does not happen when knitting to HTML, per comments in [this StackOverflow thread](http://stackoverflow.com/questions/41387561/how-to-stop-null-above-table-in-knitr-output#) I created.

Could you please take a look?

Note: Please see code in StackOverflow question, as the RMD chunk delimiters aren't working with GitHub's code delimiters.

**Comment by zeehio** [comment]
Looks like a bug. I will look into it as soon as I can. Thanks for the report and the example!

**Comment by zeehio** [comment]
Yes, my mistake. I forgot a print that should not be there. This will fix the issue until the next CRAN release. Sorry for the inconvenience.

    devtools::install_github("zeehio/condformat")

**Comment by JohnTarr** [comment]
zeehio - Thank you for the super quick response and fix. The package itself was a huge help.
