### ISSUE TITLE
Colors not being respected by 

### ISSUE THREAD

**Issue by mexindian** [zeehio/condformat#6]
Check the following case and output:

```
# Custom discrete color values can be specified with a function. The function takes
# the whole column and returns a vector with the colours.
color_pick <- function(col) {
  ifelse(col < 4.7,
         "yellow",
         ifelse(col < 4.9,
                "orange",
                "purple"))
}
condformat(head(iris)) + rule_fill_discrete_("Sepal.Length", ~ color_pick(Sepal.Length))
```
In other words, it appears the thresholds are being respected, but the colors being passed are not.

![image](https://cloud.githubusercontent.com/assets/8094091/21779211/279b0882-d66c-11e6-947a-82b9866ce956.png)

**Comment by zeehio** [comment]
I fixed the example around 20 hours ago. Note the `colours = identity`

    condformat(head(iris)) + rule_fill_discrete_("Sepal.Length",
                                                                         ~ color_pick(Sepal.Length),
                                                                          colours = identity)

![imatge](https://cloud.githubusercontent.com/assets/75441/21783466/b37fa146-d6b7-11e6-822e-281e95455aca.png)

**Comment by mexindian** [comment]
Confirmed! Thanks!
