### ISSUE TITLE
"lost" formating, when exporting to excel

### ISSUE THREAD

**Issue by jueeir** [zeehio/condformat#7]
Hi,

I'd like to color different columns in the xlsx that I create, by using several rules for the fill gradient.

Everything looks nice in the R Studio Viewer, but any then the firat rule_fill_gradient seem to be ignored by condformat2excel.

When e.g. doing the following, only column 1 is colored with a green gradient...

output <- condformat(df4) + rule_fill_gradient(1, expression = overall_score, low = "white", high = "green", na.value = "#FFFFFF") + rule_fill_gradient(2, expression = overall_score, low = "white", high = "red", na.value = "#FFFFFF")

condformat2excel(output, output.xlsx)

**Comment by zeehio** [comment]
Hi,

Thanks for reporting the issue.

It would be much easier for me to reproduce your error if you provided a fully [reproducible example](http://stackoverflow.com/a/5963610/446149).

Did you try to run this from the CRAN version or from the github version? Please try the latest development version:

```r
#install.packages("devtools")
devtools::install_github("zeehio/condformat")
```
I used this code and it worked as expected:

```r
library("condformat")
data(iris)
output <- condformat(iris) + 
  rule_fill_gradient(1, expression = Sepal.Length, low = "white", high = "green", na.value = "#FFFFFF") +
  rule_fill_gradient(2, expression = Sepal.Width, low = "white", high = "red", na.value = "#FFFFFF")

condformat2excel(output, "/tmp/output7.xlsx")
```

**Comment by zeehio** [comment]
Update: Testing the example in the latest version from CRAN seems to have the issue you describe. So this is an issue fixed in the development version that will be fixed in the next CRAN release.

In case you still have the error with the development version feel free to reopen the issue.
