### ISSUE TITLE
condformat2Latex throws error

### ISSUE THREAD

**Issue by dietrichson** [zeehio/condformat#9]
myTable <- condformat(iris[c(1:5, 70:75, 120:125), ]) +
 rule_fill_discrete(Species, colours = c("setosa" = "red",
                                         "versicolor" = "blue",
                                         "virginica" = "green")) +
 rule_fill_discrete(Sepal.Length, expression=Sepal.Length > 4.6,
                    colours=c("TRUE"="red"))

condformat2latex(myTable)

**Comment by zeehio** [comment]
Thanks for reporting this. It was a small fix. I added a test case to prevent future regressions like this.

It will be fixed on the next CRAN upload, for now you can use:

```
devtools::install_github("zeehio/condformat")
```

to install the latest development version.
